PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX dpv: <http://w3id.org/dpv#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX sdc: <https://swissdatacustodian.ch/doc/ontology#>
PREFIX sh: <http://www.w3.org/ns/shacl#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
SELECT DISTINCT ?enumerationValue ?enumerationLabel ?enumerationDefinition ?property ?propertyLabel ?group ?groupLabel
WHERE { {
  ?propertyShape a sh:PropertyShape .
        ?propertyShape sh:path ?property.
        OPTIONAL{
            ?property skos:prefLabel ?propertyLabel}
  { 
    ?propertyShape sh:class ?group .
    ?group rdfs:subClassOf sdc:EnumerationType .
    ?enumerationValue a ?group .
            ?group skos:prefLabel ?groupLabel .
            OPTIONAL{?enumerationValue skos:definition ?enumerationDefinition .}
            OPTIONAL{?enumerationValue skos:prefLabel ?enumerationLabel.}
  }
  UNION
  {
    ?propertyShape sh:or/rdf:rest*/rdf:first/sh:class ?enumerationType2 .
    ?enumerationType2 rdfs:subClassOf sdc:EnumerationType .
    ?enumerationValue a ?enumerationType2 .
            OPTIONAL{?enumerationValue skos:definition ?enumerationDefinition .}
                OPTIONAL{?enumerationValue skos:prefLabel ?enumerationLabel.}
                
  }
}
    BIND(coalesce(?enumerationType1, ?enumerationType2) as ?range)
    ?range skos:prefLabel ?rangeLabel.
    ?range skos:definition ?rangeDefinition.
}

#For each "range" we need a new concept box. The concept box should contain the "rangeLabel" as it's header, and the definition below.
#Then, for each "range", there should be a small table or other structure containing a list of the enumerationValues, with their label and definition.
#Lastly, each range should have a property "Domain" which points to the property.